# Generated by Django 3.0.9 on 2021-02-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
