# Generated by Django 3.0.9 on 2021-02-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpsv', '0002_contactpoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='pred',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
