# Generated by Django 3.0.9 on 2021-02-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpsv', '0003_contactpoint_pred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='publicservice',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website', to='cpsv.Website'),
        ),
    ]
