# Generated by Django 3.0.9 on 2021-02-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0050_auto_20210126_1136'),
        ('cpsv', '0004_auto_20210209_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservice',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ps_website', to='searchapp.Website'),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
