# Generated by Django 3.0.9 on 2021-02-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0050_auto_20210126_1136'),
        ('cpsv', '0005_auto_20210209_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpoint',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cp_website', to='searchapp.Website'),
        ),
    ]
