# Generated by Django 3.0.9 on 2021-02-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpsv', '0006_contactpoint_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpoint',
            options={'ordering': ['description']},
        ),
    ]
