version: '3'
services:
  angular:
    build: ./angular
    ports: 
      - "8080:80"
    env_file:
      - ./secrets/django-docker.env
    depends_on: 
      - django

  django:
    build: ./django
    ports:
      - "8000:8000"
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - ./django:/django
    command: ./start.sh
    restart:
      always
    depends_on:
      - postgres
      - solr
      - minio

  celery:
    build: ./django
    command: celery -A scheduler worker -l info --uid=nobody --gid=nogroup
    volumes: 
      - ./django:/django
    env_file: 
      - ./secrets/django-docker.env
    restart: 
      always
    depends_on: 
      - django
      - rabbitmq
  
  celery_beat:
    build: ./django
    command: celery -A scheduler beat -l info
    volumes: 
      - ./django:/django
    env_file: 
      - ./secrets/django-docker.env
    restart: 
      always
    depends_on: 
      - django
      - rabbitmq

  flower:
    build: ./django
    ports:
      - "5555:5555"
    command: flower -A scheduler --port=5555
    volumes: 
      - ./django:/django
    env_file: 
      - ./secrets/django-docker.env
    restart: 
      always
    depends_on: 
      - celery
    
  rabbitmq:
    image: rabbitmq
    ports: 
      - "5672:5672"

  solr:
    image: solr:8.5-slim
    ports:
      - "8983:8983"
    environment:
      - SOLR_HEAP=4g
    volumes:
      - solr:/var/solr
      - ./solr/documents:/opt/solr/server/solr/configsets/documents:ro
      - ./solr/files:/opt/solr/server/solr/configsets/files:ro
      # - ./solr/summaries:/opt/solr/server/solr/configsets/summaries:ro
    command: solr-precreate summaries #/opt/solr/server/solr/configsets/summaries

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - postgres:/var/lib/postgresql/data

  docclass:
    image: docker.crosslang.com/ctlg-manager/docclass:latest
    ports:
      - "5000:5000"

  minio:
    image: minio/minio
    command: server /data
    ports: 
      - "19000:9000"
    env_file:
      - ./secrets/django-docker.env
    volumes: 
      - minio:/data

  tika:
    image: apache/tika
    ports:
      - "9998:9998"

volumes:
  solr:
  postgres:
  minio:
