version: '3'
services:
  angular:
    build: ./angular
    ports: 
      - "8080:80"
    env_file:
      - ./secrets/django-docker.env.prod
    depends_on: 
      - django

  django:
    build: ./django
    env_file:
      - ./secrets/django-docker.env.prod
    volumes:
      - ./django:/django
      - static_volume:/django/static
      - media_volume:/django/media
    command: ./start.sh
    depends_on:
      - postgres
      - solr
      - scrapyd

  django_nginx:
    restart: always
    build: ./django/nginx
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    depends_on:
      - django
    ports:
      - "0.0.0.0:8000:8000"

  scrapyd:
    build: ./scrapy
    ports: 
      - "6800:6800"
    env_file:
      - ./secrets/django-docker.env.prod
    volumes: 
      - ./scrapy:/scrapy
    command: scrapyd

  solr:
    image: solr:8.4-slim
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr
      - ./solr/documents:/opt/solr/server/solr/configsets/documents:ro
      - ./solr/files:/opt/solr/server/solr/configsets/files:ro
    command: solr-precreate documents /opt/solr/server/solr/configsets/documents

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/django-docker.env.prod
    volumes:
      - postgres:/var/lib/postgresql/data

  docclass:
    image: docker.crosslang.com/ctlg-manager/docclass:latest
    ports:
      - "5000:5000"

volumes:
  solr:
  postgres:
  static_volume:
  media_volume:
