version: '3'
services:
  angular:
    build: ./angular
    ports: 
      - "8080:80"
    env_file:
      - ./secrets/django-docker.env.prod
    depends_on: 
      - django

  django:
    build: ./django
    env_file:
      - ./secrets/django-docker.env.prod
    volumes:
      - ./django:/django
    command: ./start.sh
    depends_on:
      - postgres
      - solr
      - scrapyd
      - minio

  django_nginx:
    restart: always
    build: ./django/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:8000:8000"

  celery:
    build: ./django
    command: celery -A scheduler worker -l info
    volumes: 
      - ./django:/django
    env_file: 
      - ./secrets/django-docker.env.prod
    restart: 
      always
    depends_on: 
      - django
      - rabbitmq

  flower:
    build: ./django
    ports:
      - "5555:5555"
    command: flower -A scheduler --port=5555
    volumes: 
      - ./django:/django
    env_file: 
      - ./secrets/django-docker.env.prod
    restart: 
      always
    depends_on: 
      - celery
    
  rabbitmq:
    image: rabbitmq
    ports: 
      - "5672:5672"

  scrapyd:
    build: ./scrapy
    ports: 
      - "6800:6800"
    env_file:
      - ./secrets/django-docker.env.prod
    volumes: 
      - ./scrapy:/scrapy
    command: scrapyd

  solr:
    image: solr:8.4-slim
    ports:
      - "8983:8983"
    volumes:
      - solr:/var/solr
      - ./solr/documents:/opt/solr/server/solr/configsets/documents:ro
      - ./solr/files:/opt/solr/server/solr/configsets/files:ro
    command: solr-precreate documents /opt/solr/server/solr/configsets/documents

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./secrets/django-docker.env.prod
    volumes:
      - postgres:/var/lib/postgresql/data

  docclass:
    image: docker.crosslang.com/ctlg-manager/docclass:latest
    ports:
      - "5000:5000"

  minio:
    image: minio/minio
    command: server /data
    ports: 
      - "19000:9000"
    env_file:
      - ./secrets/django-docker.env
    volumes:
      - minio:/data

  tika:
    image: apache/tika
    ports:
      - "9998:9998"

volumes:
  solr:
  postgres:
  minio:
