version: '3'
services:
  solr:
    image: solr:8-slim
    ports:
      - "8983:8983"
    environment:
      - SOLR_OPTS=-Ddataimporter.datasource.url=jdbc:postgresql://postgres:5432/imdb -Ddataimporter.datasource.user=django -Ddataimporter.datasource.password=django
    volumes:
      - ./solr/solrconfig.xml:/opt/solr/server/solr/configsets/_default/conf/solrconfig.xml
      - ./solr/data-config.xml:/opt/solr/server/solr/configsets/_default/conf/data-config.xml
      - ./solr/postgresql-42.2.9.jar:/opt/solr/contrib/dataimporthandler/lib/postgresql-42.2.9.jar
    command: solr-precreate imdb
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=imdb
      - POSTGRES_USER=django
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: