# Generated by Django 3.0.3 on 2020-02-25 10:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('acceptance_state', models.CharField(choices=[('Unvalidated', 'Unvalidated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unvalidated', max_length=20)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EiopaDocument',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='searchapp.Document')),
                ('title_prefix', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=200)),
            ],
            bases=('searchapp.document',),
        ),
        migrations.AddField(
            model_name='document',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='searchapp.Website'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('url', models.URLField(unique=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='searchapp.Document')),
            ],
        ),
    ]
