# Generated by Django 3.0.3 on 2020-02-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0002_auto_20200211_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='validated',
        ),
        migrations.AddField(
            model_name='document',
            name='acceptance_state',
            field=models.CharField(choices=[('Unvalidated', 'Unvalidated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unvalidated', max_length=20),
        ),
    ]
