# Generated by Django 3.0.3 on 2020-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_document_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default='', editable=False),
        ),
    ]
