# Generated by Django 3.0.3 on 2020-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0005_auto_20200211_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
