# Generated by Django 3.0.3 on 2020-02-18 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0007_auto_20200214_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 2, 18, 11, 39, 34, 898119, tzinfo=utc)),
        ),
    ]
