# Generated by Django 3.0.3 on 2020-02-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0009_auto_20200218_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
