# Generated by Django 3.0.3 on 2020-02-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0010_delete_scrapyitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'permissions': (('can_approve_dish', 'Can approve Dish publication'),)},
        ),
    ]
