# Generated by Django 3.0.3 on 2020-02-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0011_auto_20200220_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
