# Generated by Django 3.0.3 on 2020-02-24 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0013_auto_20200221_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='EiopaDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('acceptance_state', models.CharField(choices=[('Unvalidated', 'Unvalidated'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Unvalidated', max_length=20)),
                ('url', models.URLField(unique=True)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('title_prefix', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=200)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='searchapp.Website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
