# Generated by Django 3.0.3 on 2020-02-24 18:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0014_auto_20200224_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiopadocument',
            name='pfd_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to=''), default=list, size=None),
        ),
    ]
