# Generated by Django 3.0.3 on 2020-02-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0015_eiopadocument_pfd_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eiopadocument',
            old_name='pfd_files',
            new_name='pdf_files',
        ),
    ]
