# Generated by Django 3.0.3 on 2020-02-24 19:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0017_auto_20200224_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiopadocument',
            name='pdf_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='eiopa/'), default=list, editable=False, size=None),
        ),
    ]
