# Generated by Django 3.0.3 on 2020-02-24 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0018_auto_20200224_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='eiopadocument',
            name='pdf_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='eiopadocument',
            name='pdf_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='eiopa/'), default=list, size=None),
        ),
    ]
