# Generated by Django 3.0.3 on 2020-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0019_auto_20200224_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eiopadocument',
            name='pdf_files',
        ),
        migrations.AddField(
            model_name='eiopadocument',
            name='pdf_file',
            field=models.FileField(default=None, upload_to='eiopa/'),
        ),
    ]
