# Generated by Django 3.0.3 on 2020-02-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0020_auto_20200224_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eiopadocument',
            name='pdf_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
