# Generated by Django 3.0.9 on 2020-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0037_document_unvalidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
