# Generated by Django 3.0.9 on 2020-10-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0039_document_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
