# Generated by Django 3.0.9 on 2021-01-13 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0045_auto_20210105_1001'),
        ('searchapp', '0040_auto_20201022_1229'),
    ]

    operations = [
    ]
