# Generated by Django 3.0.9 on 2021-01-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0046_merge_20210113_0814'),
        ('searchapp', '0048_demo_group'),
    ]

    operations = [
    ]
