# Generated by Django 3.0.9 on 2021-01-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0049_merge_20210121_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
