# Generated by Django 3.0.9 on 2020-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0008_auto_20201029_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationworklog',
            name='end',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annotationworklog',
            name='endOffset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotationworklog',
            name='quote',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='annotationworklog',
            name='start',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='annotationworklog',
            name='startOffset',
            field=models.IntegerField(default=0),
        ),
    ]
