# Generated by Django 3.0.9 on 2020-11-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0009_auto_20201118_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationworklog',
            name='end',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='annotationworklog',
            name='start',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
