# Generated by Django 3.0.9 on 2020-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0009_merge_20201104_1222'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conceptdefined',
            name='unique_per_conceptdefined_and_document',
        ),
        migrations.RemoveConstraint(
            model_name='conceptoccurs',
            name='unique_per_conceptoccurs_and_document',
        ),
        migrations.AddConstraint(
            model_name='conceptdefined',
            constraint=models.UniqueConstraint(fields=('concept_id', 'document_id', 'begin', 'end'), name='unique_per_conceptdefined_and_document'),
        ),
        migrations.AddConstraint(
            model_name='conceptoccurs',
            constraint=models.UniqueConstraint(fields=('concept_id', 'document_id', 'begin', 'end'), name='unique_per_conceptoccurs_and_document'),
        ),
    ]
