# Generated by Django 3.0.9 on 2020-11-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0010_auto_20201119_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationworklog',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.Concept'),
        ),
    ]
