# Generated by Django 3.0.9 on 2020-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0011_annotationworklog_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationworklog',
            name='concept_defined',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='concept_occurs',
        ),
        migrations.AddField(
            model_name='annotationworklog',
            name='annotation_type',
            field=models.TextField(default='', null=True),
        ),
    ]
