# Generated by Django 3.0.9 on 2020-12-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0010_auto_20201210_1307'),
        ('glossary', '0011_auto_20201208_1608'),
    ]

    operations = [
    ]
