# Generated by Django 3.0.9 on 2020-11-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0012_auto_20201125_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationworklog',
            name='concept_defined',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.ConceptDefined'),
        ),
        migrations.AddField(
            model_name='annotationworklog',
            name='concept_occurs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.ConceptOccurs'),
        ),
    ]
