# Generated by Django 3.0.9 on 2020-12-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0013_auto_20201125_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationworklog',
            name='action',
        ),
    ]
