# Generated by Django 3.0.9 on 2021-01-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0012_merge_20201210_1350'),
        ('glossary', '0014_concept_other'),
    ]

    operations = [
    ]
