# Generated by Django 3.0.9 on 2020-12-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0014_remove_annotationworklog_action'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conceptdefined',
            name='unique_per_conceptdefined_and_document',
        ),
        migrations.RemoveConstraint(
            model_name='conceptoccurs',
            name='unique_per_conceptoccurs_and_document',
        ),
    ]
