# Generated by Django 3.0.9 on 2020-12-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0015_auto_20201210_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationworklog',
            name='annotation_type',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='document',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='end',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='endOffset',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='start',
        ),
        migrations.RemoveField(
            model_name='annotationworklog',
            name='startOffset',
        ),
        migrations.AddField(
            model_name='conceptdefined',
            name='quote',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='conceptoccurs',
            name='quote',
            field=models.TextField(default=''),
        ),
    ]
