# Generated by Django 3.0.9 on 2021-01-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0016_auto_20210112_1312'),
        ('glossary', '0015_merge_20210104_1056'),
    ]

    operations = [
    ]
