# Generated by Django 3.0.9 on 2021-01-14 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0017_merge_20210113_1352'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conceptdefined',
            name='unique_per_conceptdefined_and_document',
        ),
        migrations.RemoveConstraint(
            model_name='conceptoccurs',
            name='unique_per_conceptoccurs_and_document',
        ),
    ]
