# Generated by Django 3.0.9 on 2021-01-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0014_concept_other'),
        ('glossary', '0017_auto_20201211_1247'),
    ]

    operations = [
    ]
