# Generated by Django 3.0.3 on 2020-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='spider',
            field=models.CharField(default='', max_length=100),
        ),
    ]
