# Generated by Django 3.0.3 on 2020-02-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_scrapyitem_spider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapyitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
