# Generated by Django 3.0.3 on 2020-03-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20200224_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='spider_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
