# Generated by Django 3.0.3 on 2020-03-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_scrapingtask_spider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='scheduler_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
