# Generated by Django 3.0.3 on 2020-03-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_scrapingtask_scheduler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
