# Generated by Django 3.0.5 on 2020-06-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_delete_scrapingtaskitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingtask',
            name='spider_date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='spider_date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
