# Generated by Django 3.0.5 on 2020-06-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0008_auto_20200602_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapingtask',
            name='scheduler_id',
        ),
        migrations.CreateModel(
            name='ScrapingTaskItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_id', models.CharField(default='', max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scraping.ScrapingTask')),
            ],
        ),
    ]
