apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml -c
    kompose.image-pull-policy: Always
    kompose.image-pull-secret: crosslang
    kompose.service.expose: django.localhost
    kompose.service.expose.tls-secret: django-certificate
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  selector:
    io.kompose.service: django
status:
  loadBalancer: {}
