apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  rules:
  - host: django.ctlg-manager.95.216.185.26.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: django
          servicePort: 8000
  tls:
    - hosts:
      - django.ctlg-manager.95.216.185.26.xip.io
      secretName: django-certificate
status:
  loadBalancer: {}
