apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64 -f docker-kompose.yml convert -c
    kompose.image-pull-policy: Always
    kompose.image-pull-secret: crosslang
    kompose.service.expose: django.localhost
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64 -f docker-kompose.yml convert -c
        kompose.image-pull-policy: Always
        kompose.image-pull-secret: crosslang
        kompose.service.expose: django.localhost
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: django
    spec:
      containers:
      - args:
        - bash
        - -c
        - python manage.py makemigrations && python manage.py migrate && python manage.py
          runserver 0.0.0.0:8000
        env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: DJANGO_SECRET_KEY
              name: django-secrets-django-docker-env
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: DJANGO_ALLOWED_HOSTS
              name: django-secrets-django-docker-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: django-secrets-django-docker-env
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_HOST
              name: django-secrets-django-docker-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: django-secrets-django-docker-env
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PORT
              name: django-secrets-django-docker-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: django-secrets-django-docker-env
        - name: SOLR_URL
          valueFrom:
            configMapKeyRef:
              key: SOLR_URL
              name: django-secrets-django-docker-env
        image: docker.crosslang.com/ctlg-manager/django
        imagePullPolicy: Always
        name: django
        ports:
        - containerPort: 8000
        resources: {}
      imagePullSecrets:
      - name: crosslang
      restartPolicy: Always
status: {}
